### ISSUE TITLE
Remove a column?

### ISSUE THREAD

**Issue by laurentpayot** [brianberns/Walrus#1]
Hi @brianberns,

Walrus seems really cool, but how do you get table B that is table A minus the first column?
I guess I could do this if I knew how to access [Table.slice()](https://github.com/brianberns/Walrus/blob/87fe5fb8ea1bd6c26a28cf23b3adc6e588ed71bd/Walrus/Table.fs#L210) and the `ColumnNames` property that is displayed in a table result in my Polyglot notebook. But I could not figure out how :confused:

Thanks in advance for your help.

**Comment by brianberns** [comment]
Hi. I'm glad you're finding Walrus useful! Right now, slices are based on column names, but I could probably add a second slice operator that is based on column indexes:

```
titanic["Pclass" .. "Age"]   // current
titanic[2 .. 5]              // proposed enhancement
```

So, with this enhancement, to get table A minus the first column, you could write `A[1..]`. Would that solve your problem? If so, I'll take a look at implementing it.

**Comment by brianberns** [comment]
@laurentpayot

I made this change, and it should be available on NuGet shortly as version 1.2. I'm going to close the issue, but please let me know if you had something else in mind.

**Comment by laurentpayot** [comment]
Thank you @brianberns! Actually I didn't know the bracket syntax was for columns instead of rows. Now I'm trying to get the values (not printing) of this new table as an array of arrays or a sequence of sequences, and again I can't figure how. Do you want me to open a new issue about this? 

I guess this is all about documentation or the lack thereof. The Titanic example is quite succinct. All I'm trying to do is to get an array of labels and it's associated array of data from the [MNIST digits dataset in CSV](https://www.kaggle.com/datasets/oddrationale/mnist-in-csv). Implementing it "manually" by reading the file was trivial but I wanted to find a solution that would be as simple  and versatile as Pandas in the Python realm. Walrus is much easier to use than the object-oriented ML librairies by Microsoft, thanks for this nice piece of software 👍

**Comment by brianberns** [comment]
I think there are two problems with what you're describing

* Walrus currently assumes that you already know the table's column names. In your case, it seems this is not true? I could expose a `Table.ColumnNames` property if that would help.

* A sequence of sequences would contain a mix of weakly-typed values. Is that what you want? If so, with the change above, you could write this:

```fsharp
let data : seq<seq<obj>> =
    seq {
        for row in table.Rows do
            seq {
                for col in table.ColumnNames do
                    row.GetValue<obj>(col)
            }
    }
```

Let me know if you want me to expose the `ColumnNames` property.

**Comment by laurentpayot** [comment]
Well I did know the column names, but I did not know the `table["col2Name"..]` syntax, because of the missing docs. So, at the time, I guessed I could use [`Table.slice()`](https://github.com/brianberns/Walrus/blob/87fe5fb8ea1bd6c26a28cf23b3adc6e588ed71bd/Walrus/Table.fs#L210) that needs a `columnNames` parameter. So I needed a `Table.ColumNames` to get the 784 columns names from my MNIST dataset. But in my case by using `df["1x1"..]` it was not needed anymore.

Now you’re telling me that a `Table.ColumnNames` is needed to extract the values in a consumable way (not just for display) so yes I guess exposing a `Table.ColumnNames` property would sure help, and it can’t hurt anyway :wink: 

The `data` example you wrote is so useful that I think a `table.getData()` or a `table.extract()` function is a must, ideally with a an array of column names or indexes as a parameter. For now Walrus can only print tables in a pretty way, but not extract table data with an out-of-the-box function, am I wrong?

**Comment by brianberns** [comment]
I have exposed the `Table.ColumnNames` property and uploaded Walrus v1.3 to NuGet.

I agree that additional documentation would be useful, but it's not something I'm able to do now. Note that the Walrus API is fully discoverable via IntelliSense (with XML docs for every method, property, and function), and there are examples beyond Titanic in the unit tests, so I do think it's usable in its current state.

I'm not going to provide an `extract` function for an entire table, because it would be weakly-typed. I believe this is consistent with Deedle. (Pandas is a bit different, because Python is a dynamically-typed language.) Note that you can already extract data via `Row.GetValue`, `Row,TryGetValue`, and `Column.Values`, all of which are strongly typed.

**Comment by laurentpayot** [comment]
Fair enough, thanks!
